spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/drive_me_db?createDatabaseIfNotExist=true&characterEncoding=utf8&amp;characterSetResults=utf8mb4
    username: user
    password: password
    driver-class-name: com.mysql.jdbc.Driver
jwt:
  token:
    secret: JWTSuperSecretKey
    expiration: 10000
mail:
  host: smtp.gmail.com
  port: 587
  username: driveme.sys@gmail.com
  password: DriveMe2018
  properties:
    mail:
      smtp:
        starttls:
          enable: true
          required: true
        auth: true