spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/drive_me_db?createDatabaseIfNotExist=true&characterEncoding=utf8&amp;characterSetResults=utf8mb4
    username: user
    password: password
    driver-class-name: com.mysql.jdbc.Driver
jwt:
  token:
    secret: secret
    algorithm: algorithm
    expiration: 10000
