spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://localhost:3306/drive_me_db
    username: user
    password: password
    driver-class-name: com.mysql.jdbc.Driver
